export type Language = "fr" | "en";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { faGithub, faLinkedinIn } from "@fortawesome/free-brands-svg-icons";

export type Section = "home" | "news" | "blog";

function icon(icon: typeof faEnvelope): string {
  const [width, height, , , paths] = icon.icon;
  return `<svg viewBox="0 0 ${width} ${height}" aria-hidden="true" focusable="false">${(Array.isArray(paths) ? paths : [paths]).map(path => `<path fill="currentColor" d="${path}"></path>`).join("")}</svg>`;
}

export function escape(value = ""): string {
  return value.replace(/[&<>'"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]!);
}

export function localized(fr: string, en: string): string {
  return `<span class="fr-text" lang="fr">${fr}</span><span class="en-text" lang="en">${en}</span>`;
}

function openNonNavigationLinksInNewTab(html: string): string {
  return html.replace(/<a\b[^>]*>/g, tag => {
    const href = tag.match(/\bhref="([^"]+)"/)?.[1] ?? "";
    const external = /^(?:https?:\/\/|mailto:|tel:)/i.test(href) && !href.startsWith("https://rosasbehoundja.github.io/");
    const document = /^\/(?:assets|contents)\//.test(href);
    if ((!external && !document) || /\btarget=/.test(tag)) return tag;
    return tag.replace(/>$/, ' target="_blank" rel="noopener noreferrer">');
  });
}

export function navigation(active: Section): string {
  return `<a class="skip-link" href="#main">${localized("Aller au contenu", "Skip to content")}</a>
  <nav class="site-nav" aria-label="Main">
    <div class="nav-social" aria-label="Social links">
      <a href="mailto:perrierosas@gmail.com" aria-label="Email Rosas" title="Email">${icon(faEnvelope)}</a>
      <a href="https://github.com/rosasbehoundja" aria-label="Rosas on GitHub" title="GitHub">${icon(faGithub)}</a>
      <a href="https://www.linkedin.com/in/rosasbehoundja/" aria-label="Rosas on LinkedIn" title="LinkedIn">${icon(faLinkedinIn)}</a>
    </div>
    <div class="nav-right"><div class="nav-links">${(["home", "news", "blog"] as const).map(section => `<a href="${section === "home" ? "/" : section === "news" ? "/pages/news/" : `/pages/${section}.html`}"${section === active ? ' aria-current="page"' : ""}>${section}</a>`).join("")}</div>
    <a class="nav-cv" href="https://drive.google.com/file/d/1PuwNCgRNbc0qbkmHqzXKQxSUImPmjPZB/view?usp=sharing">CV</a>
    <button class="lang-switch" id="langBtn" type="button" hidden aria-label="Passer en français">FR</button></div>
  </nav>`;
}

interface Page {
  title: string;
  description: string;
  path: string;
  active: Section;
  body: string;
  article?: boolean;
  date?: string;
  image?: { url: string; alt: string };
  footer?: string;
  script?: string;
}

export function page(options: Page): string {
  const url = `https://rosasbehoundja.github.io${options.path}`;
  const image = options.image ?? { url: "https://rosasbehoundja.github.io/assets/media/preview.jpg", alt: "Two cartoon starfish learning in front of a whiteboard covered with formulas and a constraint graph" };
  const html = `<!DOCTYPE html>
<!-- Generated from TypeScript templates and Markdown. Do not edit this file. -->
<html lang="en" class="lang-en" prefix="og: https://ogp.me/ns# article: https://ogp.me/ns/article#">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="/assets/media/favicon_io/favicon.ico" sizes="any">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/media/favicon_io/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/media/favicon_io/favicon-16x16.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/media/favicon_io/apple-touch-icon.png">
  <link rel="manifest" href="/assets/media/favicon_io/site.webmanifest">
  <title>${escape(options.title)}</title>
  <meta name="author" content="Rosas Behoundja">
  <meta name="robots" content="index, follow">
  <meta name="description" content="${escape(options.description)}">
  <link rel="canonical" href="${url}">
  <meta property="og:title" content="${escape(options.title)}">
  <meta property="og:type" content="${options.article ? "article" : "website"}">
  <meta property="og:url" content="${url}">
  <meta property="og:description" content="${escape(options.description)}">
  <meta property="og:site_name" content="Rosas Behoundja">
  <meta property="og:locale" content="en_GB">
  <meta property="og:locale:alternate" content="fr_FR">
  <meta property="og:image" content="${escape(image.url)}">
  <meta property="og:image:alt" content="${escape(image.alt)}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escape(options.title)}">
  <meta name="twitter:description" content="${escape(options.description)}">
  <meta name="twitter:image" content="${escape(image.url)}">
  <meta name="twitter:image:alt" content="${escape(image.alt)}">
${options.date ? `<meta property="article:published_time" content="${escape(options.date)}">` : ""}
${options.active === "home" && !options.article ? '<meta name="google-site-verification" content="7LE16gRwEbXNFjLQxXWDU3iZPV9r8dh1upcFCdOlqtM">' : ""}
</head>
<body>
  ${navigation(options.active)}
  <main id="main" tabindex="-1"${options.article ? " data-article" : ""}>${options.body}</main>
  <footer class="site-footer">${options.footer ?? ""}<p>© Rosas Behoundja 2026</p></footer>
  <script type="module" src="/src/${options.script ?? (options.article ? "article" : "main")}.ts"></script>
</body>
</html>`;
  return openNonNavigationLinksInNewTab(html);
}
